### ISSUE TITLE
Enable users with OpenIDs to sign in to the node

### ISSUE THREAD

**Issue by philipkershaw** [CHARMe-Project/djcharme#2]
Currently users can only sign in with username and password for CHARMe account.  Extend so that users can link with external IDs.  This is needed for integration with ESGF.  Initial step is to support OpenID 2.0 and follow-up with OpenID Connect.

**Comment by philipkershaw** [comment]
Antony currently evaluating Python Social Auth package to implement.

**Comment by philipkershaw** [comment]
Integration of external IDs works on the principle that the user must have a CHARMe account with username/password as the default sign-in mechanism.  Users can augment this by linking other external IDs with this account.

For linking of external IDs, we need two methods.
 1) From the user profile page, an option allows the user to link to an external provider using a given protocol.  - Add support for ESGF and OpenID 2.0 initially.  
- Provide an option to associate an ESGF OpenID with the CHARMe account: the user picks from a set of known ESGF OpenID Providers (include only the CEDA one initially) in a combobox and selects 'Go';  
- they are redirect to their OpenID Provider site.  
- They sign in and redirected back to the CHARMe user profile page.  
- The CHARMe node associates the OpenID from the successful sign in with the CHARMe user account.  This allows the user to use the OpenID in subsequent logins to the node.
  
  2) This links via the node's login page:
- The user adds a new annotation and is redirected to the CHARMe node for sign in.
- The login page allows the user to sign with CHARMe username/password or use an external site.  Initially this should support ESGF OpenID 2.0 as the external option.  The UI displays a combobox listing the set of external ESGF OpenID Provider sites.
- The user picks one of the sites and is redirected to the provider site for login.
- Once logged in at the provider they are redirected back to the CHARMe node
- The node checks to see if the external ID used is associated with an existing CHARMe account.  If one is found, authentication is completed; if no matching account is found, the use is prompted to register for a CHARMe account.  This account is created with an entry linking it to the external ID.

**Comment by antony-wilson** [comment]
now deployed
